name: Tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v5

      - uses: prefix-dev/setup-pixi@v0.9.1
        with:
          manifest-path: pyproject.toml
          cache: true
          frozen: true

      - name: Execute Login Notebook
        run: |
          pixi run test
